-- Borgarland relay — schema reference.
--
-- This file documents the current shape of the database; migrations/ holds the
-- ordered changes that build it. The relay's own record of submissions lives in
-- `reports`; `addresses` is a cache of the national address registry
-- (Staðfangaskrá) that the jurisdiction check reads. Both are created by
-- migrations/0001_init.sql.
--
-- The vocabulary in these tables is ours (see src/domain.ts). The city's field
-- names, category slugs and URL never appear here.

CREATE TABLE IF NOT EXISTS reports (
  -- Our own report id (16 random hex bytes, generated by the relay). The city
  -- never sees it; it is the id the app talks about.
  id            TEXT PRIMARY KEY,
  -- Category slug as the app knows it, e.g. ruslafotur. The adapter maps it to
  -- the city's display name, type and summary at send time.
  category_slug TEXT NOT NULL,
  -- The coordinate that came with the photo, WGS84 decimal degrees. Required by
  -- us — the city enforces only description (see data/reykjavik-form.json).
  latitude      REAL NOT NULL,
  longitude     REAL NOT NULL,
  -- What we send to the city: the user's description plus the nearest
  -- registered address line (see src/domain.ts composeDescription).
  description   TEXT NOT NULL,
  email         TEXT,
  -- Photo parts are forwarded to the city but not stored here; only what they
  -- were is recorded, for the measurement layer.
  photo_count   INTEGER NOT NULL DEFAULT 0,
  photo_bytes   INTEGER NOT NULL DEFAULT 0,
  -- 1 = dry run (the default): everything happened except the city POST.
  dry_run       INTEGER NOT NULL DEFAULT 1 CHECK (dry_run IN (0, 1)),
  created_at    TEXT NOT NULL,
  -- When the city POST happened; null while the report is a dry run or the
  -- POST failed before a response.
  sent_at       TEXT,
  -- The city's HTTP status; null if the city never answered.
  city_status   INTEGER,
  -- The reference number from .../done/{number}; null if unknown.
  city_reference TEXT,
  -- 'validation' = the city rejected the content (Missing required fields);
  -- 'route' = the city answered 400 without a validator envelope (unknown
  -- route/slug); 'error' = the city answered non-2xx or never answered.
  rejection     TEXT CHECK (rejection IN ('validation', 'route', 'error')),
  -- The reporter's later answer to whether it was fixed (POST
  -- /api/reports/:id/outcome).
  outcome       TEXT CHECK (outcome IN ('fixed', 'not-fixed')),
  outcome_at    TEXT
);

CREATE INDEX IF NOT EXISTS idx_reports_created_at ON reports(created_at);

-- Staðfangaskrá rows the relay needs: the municipality code (SVFNR) for the
-- jurisdiction check and the street line for the description we send.
-- Seeded from the HMS export by scripts/refresh-registry.mjs, which writes
-- data/addresses.seed.sql; apply with:
--   wrangler d1 execute borgarland-relay --file data/addresses.seed.sql
-- The full national registry is required, not just Reykjavík: a point in
-- Kópavogur must be able to find a Kópavogur address, or the check would
-- wrongly pass it as Reykjavík (see src/registry.ts).
-- The relay fails closed (503 registry-not-loaded) until this table is seeded.
CREATE TABLE IF NOT EXISTS addresses (
  svfnr        INTEGER NOT NULL,
  street_nf    TEXT NOT NULL,
  house_number INTEGER,
  house_letter TEXT,
  postal_code  TEXT NOT NULL,
  lat          REAL NOT NULL,
  lng          REAL NOT NULL
);
